# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20160228_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bathroom_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='bed_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='size_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='vip_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='year_text',
            field=models.CharField(max_length=200),
        ),
    ]
